name: "Release"

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          
      # Fetch release data of the current repository from where the workflow is used.
      - name: Get Release data
        id: release_data
        uses: KevinRohn/github-full-release-data@v2.0.0
    
      - name: Show tag name with echo
        run: echo ${{ steps.release_data.outputs.zipball_url }}
        
      - name: mypythonaction
        uses: swamirara/github-action-python-template@1.0.1
        id: get_square
        with:
          num: 5

      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"
